### ISSUE TITLE
File `viewer_examples/6_watershed_demo.py` won't work; how to deal with QT5?

### ISSUE THREAD

**Issue by alexandrejaguar** [scikit-image/skimage-tutorials#29]
Dear all,
recently I tried to run some viewer examples, and I had an issue with `6_watershed_demo.py`. It follows:

```
jaguar@spaghetti:~/Documents/Repositories/skimage-tutorials/viewer_examples$ python 6_watershed_demo.py 
Watershed plugin
----------------
Use mouse to paint each region with a different label.
Press OK to display segmented image.
Traceback (most recent call last):
  File "6_watershed_demo.py", line 39, in <module>
    plugin += OKCancelButtons()
  File "/home/jaguar/anaconda3/lib/python3.6/site-packages/skimage/viewer/widgets/history.py", line 25, in __init__
    self.ok = QtGui.QPushButton('OK')
AttributeError: module 'PyQt5.QtGui' has no attribute 'QPushButton'
```

For PyQT5, this issue could be solved with:

```
in __init__
    self.ok = QtWidgets.QPushButton('OK')
```

in `skimage/viewer/widgets/history.py`, I think. However, this file is adapted to work also with PyQT4.
Is that right? How could we solve that?
Thanks in advance. Kind regards,

Alex

**Comment by jni** [comment]
Hi @alexandrejaguar!

I've been dealing with this issue in our conda-forge recipe. You have to force Matplotlib to use Qt4 with:

```python
import matplotlib
matplotlib.use('QtAgg')
matplotlib.rcParams['backend.qt'] = 'PyQt4'
```

I think this is the same problem anyway, not positive.

**Comment by stefanv** [comment]
Things moved around between Qt4 and Qt5.  I think the more general solution is to import from `qt_compat`:

```
from matplotlib.backends.qt_compat import QtWidgets, QtCore, QtGui
```
And to then use QtWidgets instead of QtGui.

The magic happens here:

```
# Apply shim to Qt4 APIs to make them look like Qt5               
if QT_API in (QT_API_PYQT, QT_API_PYQTv2, QT_API_PYSIDE):         
    '''Import all used QtGui objects into QtWidgets               
                                                                  
    Here I've opted to simple copy QtGui into QtWidgets as that   
    achieves the same result as copying over the objects, and will
    continue to work if other objects are used.                   
                                                                  
    '''                                                           
    QtWidgets = QtGui                                             
```

**Comment by alexandrejaguar** [comment]
Closing due to inactivity. Please reopen if necessary.
